import os
os.system ('clear')
os.system ('clear')                                                                                  
os.system ('sl')
os.system('clear')
print ('\033[1;36mحﺎﭴﻧﺑ مﺗ')
os.system ('figlet HK instagram')
print ("")
print ("")
print (" \033[1;32m بﺎﺴﺤ مﺴإ  \033[1;33m: im_lwidadi_abro_")
print ("")
print ("")
print (" \033[1;32mفﺗﺎﮩﻟ مﻗر/ ﺪﯾﺮﺑ \033[1;33m:zwamlkamlin@gmail.com")
print ("")
print ("")
print (" \033[1;32mﺮﺴㅤﺔﻤﻠڪ :\033[1;33m zwamlkolkom2022")
print ("")
print ("")
os.system ('figlet')

